version: "3.8"

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: terraterapies_db_local
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: terraterapies_local
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
