"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Button } from "./ui/button";
import { cn } from "@/app/lib/utils";
import { PromoBadge } from "@/components/ui/promo-badge";

export default function HeroCarousel({ slides }: { slides: any[] }) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPaused, setIsPaused] = useState(false); // 🚀 NEW: Interaction state

  // Auto-play interval
  useEffect(() => {
    // If there's only 1 slide, or the user has interacted, stop the auto-play!
    if (slides.length <= 1 || isPaused) return;

    const interval = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % slides.length);
    }, 5000); // Change image every 5 seconds

    return () => clearInterval(interval);
  }, [slides.length, isPaused]);

  if (slides.length === 0) return null;

  return (
    <div className="relative w-full aspect-[4/5] md:aspect-[21/9] rounded-2xl overflow-hidden shadow-2xl border border-border group bg-muted mt-12 mb-8">
      {slides.map((slide, index) => {
        // Destructure the properties generated by the Server Hydration
        const {
          resolvedTitle,
          resolvedSubtitle,
          resolvedLink,
          resolvedButtonText,
          promoBadgeText,
          desktopUrl,
          mobileUrl,
        } = slide;

        return (
          <div
            key={slide.id}
            className={cn(
              "absolute inset-0 transition-opacity duration-1000 ease-in-out",
              index === currentIndex ? "opacity-100 z-10" : "opacity-0 z-0",
            )}
          >
            {/* Mobile Image (Hidden on Desktop) */}
            {mobileUrl && (
              <img
                src={mobileUrl}
                alt={resolvedTitle}
                className="w-full h-full object-cover block md:hidden"
              />
            )}

            {/* Desktop Image (Hidden on Mobile) */}
            {desktopUrl && (
              <img
                src={desktopUrl}
                alt={resolvedTitle}
                className="w-full h-full object-cover hidden md:block"
              />
            )}

            {/* 🚀 PROMO BADGE (Moved after images, high z-index) */}
            <PromoBadge
              text={promoBadgeText}
              className="absolute top-6 right-6 z-30 scale-110"
            />

            {/* Dark Gradient Overlay so text is readable */}
            {/* New: Elegant, brand-aligned dark shadow */}
            <div className="absolute inset-0 bg-gradient-to-t from-foreground/90 via-foreground/40 to-transparent z-10" />

            {/* Marketing Overlay Content */}
            {(resolvedTitle || resolvedSubtitle) && (
              <div className="absolute bottom-0 left-0 right-0 p-6 md:p-12 text-center md:text-left text-primary-foreground z-20">
                <div className="max-w-3xl mx-auto md:mx-0" data-aos="fade-up">
                  {resolvedTitle && (
                    <h3 className="text-3xl md:text-5xl font-bold mb-3 drop-shadow-md">
                      {resolvedTitle}
                    </h3>
                  )}
                  {resolvedSubtitle && (
                    <p className="text-lg md:text-xl text-primary-foreground/80 mb-6 drop-shadow-md line-clamp-2 md:line-clamp-none">
                      {resolvedSubtitle}
                    </p>
                  )}
                  {resolvedLink && resolvedButtonText && (
                    <Button
                      asChild
                      size="lg"
                      variant="default"
                      className="shadow-xl ring-1 ring-border/20"
                    >
                      <Link href={resolvedLink}>{resolvedButtonText}</Link>
                    </Button>
                  )}
                </div>
              </div>
            )}
          </div>
        );
      })}

      {/* Manual Navigation Dots */}
      {slides.length > 1 && (
        <div className="absolute bottom-4 left-0 right-0 flex justify-center gap-2 z-30">
          {slides.map((_, i) => (
            <button
              key={i}
              onClick={() => {
                setCurrentIndex(i);
                setIsPaused(true); // 🚀 Stop auto-play when user clicks!
              }}
              className={cn(
                "w-2.5 h-2.5 rounded-full transition-all duration-300 shadow-sm",
                i === currentIndex
                  ? "bg-primary scale-125" // 🚀 Active dot uses brand color!
                  : "bg-primary-foreground/50 hover:bg-primary-foreground/80",
              )}
              aria-label={`Go to slide ${i + 1}`}
            />
          ))}
        </div>
      )}
    </div>
  );
}
